# Generated by Django 5.0.2 on 2024-04-02 13:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('authentication', '0001_initial'),
        ('property', '0001_initial'),
    ]


